#!/usr/bin/env python3
"""Render contact sheets from a 2D point-grounding manifest."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Sequence, Tuple

from PIL import Image, ImageDraw, ImageFont


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render top-K frame contact sheets with projected GT points.")
    parser.add_argument("--manifest", required=True, help="Path to manifest_all.csv generated by build_2d_eval_manifest.py")
    parser.add_argument("--output_dir", default="exam2/outputs/contact_sheets", help="Output directory for contact sheets.")
    parser.add_argument("--max_sheets", type=int, help="Maximum number of row-level sheets to render.")
    parser.add_argument("--panel_width", type=int, default=360, help="Rendered panel width. Default: 360")
    parser.add_argument("--panel_height", type=int, default=240, help="Rendered panel height. Default: 240")
    parser.add_argument("--columns", type=int, default=5, help="Contact sheet columns. Default: 5")
    parser.add_argument("--draw_invalid", action="store_true", help="Also list invalid projections in the legend.")
    return parser.parse_args()


def read_manifest(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def normalize_text(value: Any) -> str:
    return "" if value is None else str(value).strip()


def parse_float(value: Any) -> float | None:
    text = normalize_text(value)
    if not text:
        return None
    try:
        return float(text)
    except ValueError:
        return None


def group_rows(rows: Sequence[Mapping[str, str]]) -> Dict[Tuple[str, str], List[Mapping[str, str]]]:
    grouped: Dict[Tuple[str, str], List[Mapping[str, str]]] = defaultdict(list)
    for row in rows:
        if not normalize_text(row.get("panel_id")):
            continue
        grouped[(normalize_text(row.get("scene")), normalize_text(row.get("row_index")))].append(row)
    return grouped


def load_font() -> ImageFont.ImageFont:
    try:
        return ImageFont.truetype("arial.ttf", 16)
    except OSError:
        return ImageFont.load_default()


def color_for_index(index: int) -> Tuple[int, int, int]:
    palette = [
        (255, 59, 48),
        (52, 199, 89),
        (0, 122, 255),
        (255, 149, 0),
        (175, 82, 222),
        (90, 200, 250),
        (255, 45, 85),
        (191, 90, 242),
    ]
    return palette[index % len(palette)]


def resize_with_letterbox(image: Image.Image, size: Tuple[int, int]) -> Tuple[Image.Image, float, int, int]:
    target_w, target_h = size
    src_w, src_h = image.size
    scale = min(target_w / src_w, target_h / src_h)
    new_w = max(1, int(src_w * scale))
    new_h = max(1, int(src_h * scale))
    resized = image.resize((new_w, new_h), Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", size, (24, 24, 24))
    offset_x = (target_w - new_w) // 2
    offset_y = (target_h - new_h) // 2
    canvas.paste(resized, (offset_x, offset_y))
    return canvas, scale, offset_x, offset_y


def render_sheet(
    key: Tuple[str, str],
    rows: Sequence[Mapping[str, str]],
    output_dir: Path,
    panel_size: Tuple[int, int],
    columns: int,
    font: ImageFont.ImageFont,
    draw_invalid: bool,
) -> Path | None:
    scene, row_index = key
    panels = sorted({normalize_text(row.get("panel_id")) for row in rows if normalize_text(row.get("panel_id"))})
    if not panels:
        return None
    panel_to_rows = {panel: [row for row in rows if normalize_text(row.get("panel_id")) == panel] for panel in panels}
    panel_paths = {panel: Path(normalize_text(panel_to_rows[panel][0].get("frame_path"))) for panel in panels}
    if not any(path.exists() for path in panel_paths.values()):
        return None

    columns = max(1, columns)
    rows_count = int(math.ceil(len(panels) / columns))
    panel_w, panel_h = panel_size
    label_h = 28
    gutter = 10
    legend_h = 90
    sheet_w = columns * panel_w + (columns + 1) * gutter
    sheet_h = rows_count * (panel_h + label_h) + (rows_count + 1) * gutter + legend_h
    sheet = Image.new("RGB", (sheet_w, sheet_h), (18, 18, 18))
    draw = ImageDraw.Draw(sheet)

    referents = sorted({normalize_text(row.get("referent_name")) for row in rows if normalize_text(row.get("referent_name"))})
    referent_colors = {name: color_for_index(index) for index, name in enumerate(referents)}

    instruction = normalize_text(rows[0].get("instruction"))
    for idx, panel in enumerate(panels):
        row_pos = idx // columns
        col_pos = idx % columns
        x0 = gutter + col_pos * (panel_w + gutter)
        y0 = gutter + row_pos * (panel_h + label_h + gutter)
        image_path = panel_paths[panel]
        if image_path.exists():
            image = Image.open(image_path).convert("RGB")
            source_w, source_h = image.size
            panel_image, scale, ox, oy = resize_with_letterbox(image, panel_size)
        else:
            source_w = parse_float(panel_to_rows[panel][0].get("image_width")) or panel_w
            source_h = parse_float(panel_to_rows[panel][0].get("image_height")) or panel_h
            panel_image = Image.new("RGB", panel_size, (48, 48, 48))
            scale = 1.0
            ox = oy = 0
        sheet.paste(panel_image, (x0, y0))
        draw.rectangle((x0, y0, x0 + panel_w, y0 + panel_h), outline=(120, 120, 120), width=1)
        frame_time = normalize_text(panel_to_rows[panel][0].get("frame_time"))
        draw.text((x0 + 6, y0 + panel_h + 5), f"{panel}  t={frame_time}s", fill=(235, 235, 235), font=font)

        for point_row in panel_to_rows[panel]:
            if normalize_text(point_row.get("projection_valid")) != "True":
                continue
            referent = normalize_text(point_row.get("referent_name"))
            gt_x = parse_float(point_row.get("gt_x"))
            gt_y = parse_float(point_row.get("gt_y"))
            img_w = parse_float(point_row.get("image_width")) or source_w
            img_h = parse_float(point_row.get("image_height")) or source_h
            if gt_x is None or gt_y is None or img_w <= 0 or img_h <= 0:
                continue
            px = x0 + ox + gt_x * scale
            py = y0 + oy + gt_y * scale
            color = referent_colors.get(referent, (255, 255, 255))
            radius = 6
            draw.ellipse((px - radius, py - radius, px + radius, py + radius), outline=color, width=3)
            draw.text((px + 8, py - 8), referent, fill=color, font=font)

    legend_y = sheet_h - legend_h + 8
    draw.text((gutter, legend_y), f"{scene} row_{row_index}: {instruction[:140]}", fill=(245, 245, 245), font=font)
    legend_y += 24
    x = gutter
    for name in referents:
        color = referent_colors[name]
        draw.rectangle((x, legend_y + 4, x + 14, legend_y + 18), fill=color)
        draw.text((x + 20, legend_y), name, fill=(235, 235, 235), font=font)
        x += 20 + max(80, len(name) * 9)
        if x > sheet_w - 160:
            x = gutter
            legend_y += 24
    if draw_invalid:
        invalid = [row for row in rows if normalize_text(row.get("projection_valid")) != "True"]
        if invalid:
            draw.text((gutter, sheet_h - 24), f"Invalid projections: {len(invalid)}", fill=(180, 180, 180), font=font)

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{scene}_row_{row_index}.jpg"
    sheet.save(output_path, quality=92)
    return output_path


def main() -> None:
    args = parse_args()
    manifest_path = Path(args.manifest)
    output_dir = Path(args.output_dir)
    rows = read_manifest(manifest_path)
    grouped = group_rows(rows)
    font = load_font()
    rendered = 0
    for key in sorted(grouped, key=lambda item: (item[0], int(item[1]) if item[1].isdigit() else item[1])):
        if args.max_sheets is not None and rendered >= args.max_sheets:
            break
        output_path = render_sheet(
            key,
            grouped[key],
            output_dir,
            (args.panel_width, args.panel_height),
            args.columns,
            font,
            args.draw_invalid,
        )
        if output_path is not None:
            rendered += 1
            print(f"Rendered {output_path}")
    print(f"Rendered sheets: {rendered}")


if __name__ == "__main__":
    main()

